/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 car.gltf
Author: Veisun (https://sketchfab.com/Veisun)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nissan-leopard-ultima-1986-luxury-edition-cb2d001f6051458fa614c821197f6583
Title: Nissan Leopard Ultima [1986] (Luxury Edition)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/car.gltf')
  return (
    <group {...props} dispose={null} scale={1.2} rotation={[0.3,-0.6,0]} >
      {/* <group rotation={[Math.PI / 2, 0, 0]}> */}
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_34.geometry} material={materials.numberplate} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.plastic} />
        
      </group>
      <group position={[0.74, 0.32, 1.3]} rotation={[-0.63, 0, Math.PI / 2]} scale={[0.25, 0.23, 0.25]}>
        <mesh geometry={nodes.Object_37.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.Object_38.geometry} material={materials['Material.021']} />
        <mesh geometry={nodes.Object_39.geometry} material={materials['Material.023']} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_41.geometry} material={materials['.001']} />
        <mesh geometry={nodes.Object_42.geometry} material={materials['.007']} />
      </group>
      <group position={[0.74, 0.32, -1.33]} rotation={[-0.63, 0, Math.PI / 2]} scale={[0.25, 0.23, 0.25]}>
        <mesh geometry={nodes.Object_44.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Object_45.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_46.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_47.geometry} material={materials['.010']} />
        <mesh geometry={nodes.Object_48.geometry} material={materials['.009']} />
        <mesh geometry={nodes.Object_49.geometry} material={materials['.008']} />
      </group>
      <group position={[-0.74, 0.32, 1.3]} rotation={[-2.51, 0, -Math.PI / 2]} scale={[0.25, 0.23, 0.25]}>
        <mesh geometry={nodes.Object_51.geometry} material={materials['Material.006']} />
        <mesh geometry={nodes.Object_52.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Object_53.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_54.geometry} material={materials['.013']} />
        <mesh geometry={nodes.Object_55.geometry} material={materials['.012']} />
        <mesh geometry={nodes.Object_56.geometry} material={materials['.011']} />
      </group>
      <group position={[-0.74, 0.32, -1.33]} rotation={[-2.51, 0, -Math.PI / 2]} scale={[0.25, 0.23, 0.25]}>
        <mesh geometry={nodes.Object_58.geometry} material={materials['Material.009']} />
        <mesh geometry={nodes.Object_59.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Object_60.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Object_61.geometry} material={materials['.016']} />
        <mesh geometry={nodes.Object_62.geometry} material={materials['.015']} />
        <mesh geometry={nodes.Object_63.geometry} material={materials['.014']} />
      </group>
      <mesh geometry={nodes.Object_4.geometry} material={materials.color_car} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.GLASS_shader} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.plastic_car} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.chrome_car} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.focus} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['glass_orng.']} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.mirror_car} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.kl_car} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.chrome_car} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.focus} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['.002']} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.LEOPARD_LETTERING} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.color_car} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.chrome_car} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.GLASS_red} />
      <mesh geometry={nodes.Object_24.geometry} material={materials['glass_orng.']} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.GLASS_shader_normals} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.GLASS_shader_headloght} />
      <mesh geometry={nodes.Object_28.geometry} material={materials.plastic_car} />
      <mesh geometry={nodes.Object_30.geometry} material={materials['LEOPARD_LETTERING.001']} />
      <mesh geometry={nodes.Object_32.geometry} material={materials['antenna.plastic']} rotation={[-Math.PI, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/car.gltf')
